language: python
python: 2.7
sudo: true
os:
  - linux
env:
  - TOX_ENV=lint
  - TOX_ENV=py27
  - TOX_ENV=integration VAULT_TOKEN="st2token" VAULT_ADDR="http://127.0.0.1:8200"
services:
  - docker

install:
  - pip install tox

script:
  - if [ "$TOX_ENV" == "integration" ]; then sudo wget -nv https://releases.hashicorp.com/vagrant/2.1.2/vagrant_2.1.2_i686.deb; fi
  - if [ "$TOX_ENV" == "integration" ]; then sudo dpkg -i vagrant_2.1.2_i686.deb; fi
  - if [ "$TOX_ENV" == "integration" ]; then sudo ln -s `which ruby` /opt/vagrant/embedded/bin/ruby; fi
  - if [ "$TOX_ENV" == "integration" ]; then vagrant up;
  - tox -e $TOX_ENV
  - if [ "$TOX_ENV" == "integration" ]; then vagrant destroy; fi
