language: python
sudo: true
os:
  - linux

jobs:
  include:
    - python: "2.7"
      env:
        - TOX_ENV=lint
        - TOX_ENV=py27
        - TOX_ENV=integration VAULT_TOKEN="st2token" VAULT_ADDR="http://127.0.0.1:8200"
    - python: "3.6"
      env:
        - TOX_ENV=lint
        - TOX_ENV=py36
        - TOX_ENV=integration VAULT_TOKEN="st2token" VAULT_ADDR="http://127.0.0.1:8200"

services:
  - docker

install:
  - pip install tox

script:
  - if [ "$TOX_ENV" == "integration" ]; then sudo wget -nv https://releases.hashicorp.com/vagrant/2.1.2/vagrant_2.1.2_i686.deb; fi
  - if [ "$TOX_ENV" == "integration" ]; then sudo dpkg -i vagrant_2.1.2_i686.deb; fi
  # Next two lines are due to a bug in Vagrant packaging, see:
  # https://github.com/hashicorp/vagrant/issues/9647
  - if [ "$TOX_ENV" == "integration" ]; then sudo rm /opt/vagrant/embedded/bin/ruby; fi
  - if [ "$TOX_ENV" == "integration" ]; then sudo ln -s `which ruby` /opt/vagrant/embedded/bin/ruby; fi
  - if [ "$TOX_ENV" == "integration" ]; then vagrant up; fi
  - tox -e $TOX_ENV
